### ISSUE TITLE
Error running deepgif

### ISSUE THREAD

**Issue by resparks** [fepegar/highresnet#10]
* highresnet version: 0.7.1
* Python version: 3.7.4.
* Operating System: Windows 10

### Description
Error when running deepgif in conda environment (conda version 4.7.12). When I revert to highresnet==0.4.1 the error resolves. 

### What I Did

```
(base) C:\ProgramData\Miniconda3>deepgif -h
Traceback (most recent call last):
  File "c:\programdata\miniconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\programdata\miniconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Miniconda3\Scripts\deepgif.exe\__main__.py", line 4, in <module>
ModuleNotFoundError: No module named 'highresnet.cli'
```

**Comment by fepegar** [comment]
Fixed in 07bd25d699178ef0f4a6d72671734b1932d0eaed

Thanks, Rachel.
